version: '3'

services:
  
   
  admin:        
    image: viji27/groceryproduct
    ports:
      - 8081:8081
     
  

  postgres:        
    image: postgres:13.3
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2707
      POSTGRES_DB: groceryproduct

    volumes:
      - pgdata:/var/lib/postgresql/data

 
volumes:
  pgdata:    
    
 

    

   
